function [fitresult, gof] = R_createFit(X_fit, Y_fit, Z_fit,Xc,Yc)
%CREATEFIT(X1_FIT,Y1_FIT,Z1_FIT)
%  Create a fit.
%
%  Data for 'fittedmodel_1deg' fit:
%      X Input : X1_fit
%      Y Input : Y1_fit
%      Z Output: Z1_fit
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Sep-2018 16:07:24


%% Fit: 'fittedmodel_1deg'.
[xData, yData, zData] = prepareSurfaceData( X_fit, Y_fit, Z_fit );

% Set up fittype and options.
ft = fittype( 'a+b*exp(-c*(x-e)^2-d*(y-f)^2)', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 1 1];
% opts.StartPoint = [890 5900 0.001 0.001 Yc Xc];
% opts.Upper = [10000 65000 1 1 3000 3000];
opts.StartPoint = [0.5 300000 0.001 0.001 Yc Xc]; %subpixel frames
opts.Upper = [Inf Inf 1 1 1500 1500]      ; %subpixel
% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.

%figure( 'Name', 'fittedmodel' );
h=plot( fitresult, [xData, yData], zData );
legend( h, 'fittedmodel_1deg', 'Z_fit vs. X_fit, Y_fit', 'Location', 'NorthEast' );
 % Label axes
xlabel X_fit
ylabel Y_fit
zlabel Z_fit
grid on


%coeff = coeffvalues(fitresult);
